name: "Build"

on:
  push:
    branches:
  pull_request:
    branches:
  workflow_dispatch:

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Install tools
        run: dotnet tool restore

      - name: Run Fantomas
        run: dotnet fantomas . --recurse --check

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test
